### ISSUE TITLE
 Possible XSS at input fields

### ISSUE THREAD

**Issue by sebastianneubert** [koalamon/Koalamon#75]
Avoid any JS in inputs (integration configuration) at koalamon.

**Comment by koalamon** [comment]
Added {{ string | secure }} twig tag to TwigContentBundle. Using it when outputting the event message.

@sebastianneubert is this enough?

**Comment by sebastianneubert** [comment]
Maybe its enough. I'll check the new twig-filter.

**Comment by koalamon** [comment]
Tried some stuff, looks good.
